version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      crypto:
        patterns:
          - "aes"
          - "aes-gcm"
          - "ccm"
          - "chacha20poly1305"
          - "cipher"

  - package-ecosystem: npm
    directory: /tagotip-node
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /tagotip-python
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /tagotip-go
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
